# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alec's blog of things
email: alec.parks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        A personal site set up for my own musings and thoughts.
        Possibly about amateur radio, Java/Kotlin, and C# for now.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alec-parks.github.io" # the base hostname & protocol for your site
twitter_username: himrin
github_username:  alec-parks

# Build settings
markdown: kramdown
